[package]
name = "bad-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Command-line interface for libbad"

[[bin]]
name = "bad"
path = "src/main.rs"

[dependencies]
libbad = { path = "../libbad" }
